### ISSUE TITLE
animate latex package

### ISSUE THREAD

**Issue by Tokariew** [Cimbali/pympress#102]
# Environment
- Windows 10 1809 64bit

# Pympress
- version 1.2
- Installation method:  binary installer vlc 64 bit?

# Expected behaviour 
Displaying correctly animation created with animate package
# Steps to reproduce

minimal example
```
\documentclass{beamer}
\usepackage{animate}

\title{problem}

\begin{document}

\begin{frame}
 \titlepage
\end{frame}
\begin{frame}
 not as much broken
\end{frame}

\begin{frame}{Animation}
 \animategraphics[width=1\linewidth,type=jpg]{16}{img-}{1}{10}
\end{frame}

\end{document}

```
# Problem
In the example, presenter show only first frame, and content show second frame with some delay. Trying to show frame with animation result with black screen for content window.

pympress.log
```
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\bscuser\Documents\pympress\pympress\surfacecache.py", line 293, in renderer
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 611, in page
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 207, in __init__
AttributeError: 'NoneType' object has no attribute 'any'
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\bscuser\Documents\pympress\pympress\surfacecache.py", line 293, in renderer
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 611, in page
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 207, in __init__
AttributeError: 'NoneType' object has no attribute 'any'
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\bscuser\Documents\pympress\pympress\surfacecache.py", line 293, in renderer
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 611, in page
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 207, in __init__
AttributeError: 'NoneType' object has no attribute 'any'
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "C:\Users\bscuser\Documents\pympress\pympress\ui.py", line 843, in on_navigation
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 678, in goto_next
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 666, in goto
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 651, in _do_page_change
  File "C:\Users\bscuser\Documents\pympress\pympress\ui.py", line 660, in on_page_change
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 630, in next_page
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 611, in page
  File "C:\Users\bscuser\Documents\pympress\pympress\document.py", line 207, in __init__
AttributeError: 'NoneType' object has no attribute 'any'
````

**Comment by Cimbali** [comment]
I’ll look into it. A good workaround is to make the animation into a gif and embed that ass an image. Those are already supported.

**Comment by Cimbali** [comment]
Can you also try with a higher level of verbosity? I think we might be missing some earlier more helpful message, e.g. which annotation is unsupported or something like that. Try `pympress --log=debug`
