### ISSUE TITLE
Embedded video is not played

### ISSUE THREAD

**Issue by eddrog** [Cimbali/pympress#125]
# Environment
- Windows 7

# Pympress
- 1.5.1
- binary installer

# Expected behaviour 
- The embedded video is played like in version 1.4.1

# Problem
- Embedded video in a pdf is not played if I click on it and the play button with scroller is not shown

**Comment by eddrog** [comment]
ERROR:pympress.extras:Videounterstützung auf Basis von GStreamer ist deaktiviert.
Traceback (most recent call last):
  File "C:\projects\pympress/pympress/extras.py", line 408, in _setup_backends
  File "C:\projects\pympress/pympress/media_overlays/gst_backend.py", line 35, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
ValueError: Namespace Gst not available
ERROR:pympress.extras:Videounterstützung auf Basis von VLC ist deaktiviert.
Traceback (most recent call last):
  File "C:\projects\pympress/pympress/extras.py", line 425, in _setup_backends
  File "C:\projects\pympress/pympress/media_overlays/vlc_backend.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:/msys64/mingw64/lib/python3.8/site-packages/vlc.py", line 207, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/vlc.py", line 163, in find_lib
  File "C:/msys64/mingw64/lib/python3.8/ctypes/__init__.py", line 369, in __init__
FileNotFoundError: Could not find module 'libvlc.dll'. Try using the full path with constructor syntax.
INFO:__main__:Pympress: 1.5.1 ; Python: 3.8.0 ; OS: Windows 7 ; Gtk 3.24.12 ; GLib 2.62.1 ; Poppler 0.82.0 cairo ; Cairo 1.16.0 , pycairo 1.18.2 ; Media: Gif-Wiedergabe mit GtkImage
WARNING:pympress.extras:No available overlay for mime type video/mp4, ignoring media C:\Users\ROGALS~1.FIS\AppData\Local\Temp\pdf_embed_zaeq6431.mp4

**Comment by eddrog** [comment]
GStreamer: video support is deactived
VLC: video support is deactived

**Comment by Cimbali** [comment]
None of the video backends is installed. `Gst` is still a little experimental, and not shipped by default in Windows installers, however VLC should work. It fails with a rather clear error:

    FileNotFoundError: Could not find module 'libvlc.dll'. Try using the full path with constructor syntax.

- Is VLC installed on your system?
- Is it installed with the same bitness (i.e. if you installed pympress x86_64, did you use the 64 bit installer from VLC? if you used pympress i686, did you use the 32 bit installer from VLC?)

The vlc python bindings do a lot of work to find the python DLL, checking registry entries, default locations, etc. If that still doesn’t work, for some reason, try setting the environment variable `PYTHON_VLC_LIB_PATH` to the full path to `libvlc.dll`

**Comment by eddrog** [comment]
Is it installed with the same bitness (i.e. if you installed pympress x86_64, did you use the 64 bit installer from VLC?
Yes.

![image](https://user-images.githubusercontent.com/1674106/70069003-52e0fe80-15f1-11ea-91cd-f9ecc1225c26.png)

**Comment by Cimbali** [comment]
Can you show the log file corresponding to a run that works? (delete it, and restart pympress with `PYTHON_VLC_LIB_PATH`). It should give us information on VLC versions etc.

**Comment by eddrog** [comment]
ERROR:pympress.extras:Videounterstützung auf Basis von GStreamer ist deaktiviert.
Traceback (most recent call last):
  File "C:\projects\pympress/pympress/extras.py", line 408, in _setup_backends
  File "C:\projects\pympress/pympress/media_overlays/gst_backend.py", line 35, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
ValueError: Namespace Gst not available
INFO:__main__:Pympress: 1.5.1 ; Python: 3.8.0 ; OS: Windows 7 ; Gtk 3.24.13 ; GLib 2.62.1 ; Poppler 0.82.0 cairo ; Cairo 1.16.0 , pycairo 1.18.2 ; Media: Gif-Wiedergabe mit GtkImage, VLC 3.0.8 Vetinari
