### ISSUE TITLE
Can't play videos in presentation

### ISSUE THREAD

**Issue by tom-doerr** [Cimbali/pympress#161]
### Environment
Ubuntu 20.04
Python 3.8.2

### Pympress
1.5.3
Pip

### Expected behaviour
I expect a video in the presentation to play, but it doesn't. 
The videos works when I open the presentation in Okular on a system running Linux Mint 19 (based on Ubuntu 18.04).
When I open the same presentation in Okular on my Ubuntu 20.04 machine it doesn't work.

### Problem
Among other output, pympress prints the following in the terminal:
```
ERROR:pympress.extras:Video support using GStreamer is disabled.
```
This is a result of pympress being unable to execute the following import:
```

[nav] In [5]:                 from pympress.media_overlays.gst_backend import GstOverlay 
         ...:                                                                                             
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-1151950c62ad> in <module>
----> 1 from pympress.media_overlays.gst_backend import GstOverlay

~/Nextcloud/Uni/dlcg/praesentation/venv/lib/python3.8/site-packages/pympress/media_overlays/gst_backend.py in <module>
     32 gi.require_version('Gtk', '3.0')
     33 gi.require_version('Gst', '1.0')
---> 34 gi.require_version('GstPlayer', '1.0')
     35 from gi.repository import GLib, Gst, GstPlayer
     36 

~/Nextcloud/Uni/dlcg/praesentation/venv/lib/python3.8/site-packages/gi/__init__.py in require_version(namespace, version)
    127     available_versions = repository.enumerate_versions(namespace)
    128     if not available_versions:
--> 129         raise ValueError('Namespace %s not available' % namespace)
    130 
    131     if version not in available_versions:

ValueError: Namespace GstPlayer not available

[ins] In [6]:    
```
So the issue seems to be that the GstPlayer in version 1.0 is not installed on my system, but I couldn't figure out how to install it.
I did follow the pympress installation instructions and tried the pip version as well as the apt version. 

The pympress.log contains 72k lines, so I didn't post it.

Any idea how to fix the issue?

**Comment by Cimbali** [comment]
Gstreamer support in pympress is not the most stable. Can you try installing vlc, see if that works?

For the log file you can simply delete it and restart pympress to get the error messages in a shorter file.

**Comment by tom-doerr** [comment]
I do have vlc installed: `VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)`
After I deleted the log file and restarted pympress multiple times no log file is written.
The file should be in `/home/tom/.cache/pympress.log`, but there is no such file
```
$ wc  /home/tom/.cache/pympress.log:
wc: /home/tom/.cache/pympress.log: No such file or directory
```

**Comment by tom-doerr** [comment]
Just installed pympress outside of my virtualenv, now the log is written:
```
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.8/site-packages/pympress/util.py", line 81, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/tom/.local/lib/python3.8/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
ERROR:pympress.extras:Video support using GStreamer is disabled.
INFO:pympress.extras:Caused by ValueError: Namespace GstPlayer not available
INFO:pympress.__main__:Pympress: 1.5.3 ; Python: 3.8.2 ; OS: Linux 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 ; Gtk 3.24.18 ; GLib 2.64.2 ; Poppler 0.86.1 cairo ; Cairo 1.16.0 , pycairo 1.16.2 ; Media: GtkImage gif player, VLC 3.0.9.2 Vetinari
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
INFO:pympress.document:Pympress does not yet support link type "<enum POPPLER_ACTION_NAMED of type Poppler.ActionType>" to "Find"
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.8/site-packages/pympress/util.py", line 81, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/tom/.local/lib/python3.8/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
ERROR:pympress.ui:Error loading icon for about window
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.8/site-packages/pympress/ui.py", line 521, in menu_about
    about.set_logo(GdkPixbuf.Pixbuf.new_from_file(util.get_icon_path('pympress-128.png')))
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/tom/.local/lib/python3.8/site-packages/pympress/share/pixmaps/pympress-128.png”: No such file or directory (4)
```

**Comment by Cimbali** [comment]
Alright, can you share the latex code you use? I suspect you're not using `\movie` from the `multimedia` package?

**Comment by tom-doerr** [comment]
I also tried to use `\movie` without success.
The video that is playing on my Linux Mint machine in okular is using `\includemedia`, but even that isn't working on my Ubuntu 20.04 machine. 
Here's the latex source: https://v22016124111441558.luckysrv.de/index.php/s/zoAAWzDWrLXN5E4

**Comment by virsto** [comment]
An interesting feature (or bug) in vers. 1.5.3. I have an embedded mp4 file inside a PDF and when I view it in Power PDF Standard 2 -- no problem with playing it with VLC. However, if I load the PDF with pympress, I must first hit the Return key before I click on it. That is, I get a "hand" icon when I hit the Return key and then and only then am I able to play the video with VLC. 
[Video_test_08.pdf](https://github.com/Cimbali/pympress/files/4875215/Video_test_08.pdf). The following might be useful in fixing this:
windows 10 Vers: 10.0.18363.900
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
beamer: 3.58 Vers. 2020-05-06
media embedded by media9 [1.11(2020/05/06)]
flashplayer32pp_xa_acr_install: Vers. 2.0.0.518
VLC Vers: 3.0.11
pympress Vers. 1.5.3

**Comment by virsto** [comment]
Oops! forgot to attach the test.mp4 and test.jpg
![test](https://user-images.githubusercontent.com/1046843/86537014-60929580-beec-11ea-8103-0ce5d3f84b16.jpg)

You did not allow me to attach my test.mp4

**Comment by Cimbali** [comment]
As far as I can tell `\movie` works in your examples @tom-doerr, if you either specify:
- a width and a height
- a placeholder (first argument to `\movie{}`).

Otherwise the PDF annotation that holds the video has a 0 size (in 1 or 2 dimensions) and so you can’t find it to click on it. So both of these examples work (with frames purely to see where the movie widgets are):

```latex
\documentclass{beamer}
\usepackage{multimedia}

\begin{document}
\begin{frame}
   \fbox{
      \movie{\rule{4.5cm}{3cm}}{videos/teaser.mp4}
   }
   \fbox{
      \movie[width=4.5cm,height=3cm]{}{videos/teaser.mp4}
   }
\end{frame}
\end{document}
```

**Comment by Cimbali** [comment]
>  media embedded by media9 [1.11(2020/05/06)]
> flashplayer32pp_xa_acr_install: Vers. 2.0.0.518

@virsto can you try using `\movie` from the multimedia package? That way it is included directly and not via a flash player.

**Comment by Cimbali** [comment]
Closing for now as the problems seem solved. Feel free to reopen if I missed something or there is new information.
