### ISSUE TITLE
Will Not Start on Fedora 

### ISSUE THREAD

**Issue by rikiheck** [Cimbali/pympress#183]
After installing the Fedora package from the copr, I get:

Traceback (most recent call last):
  File "/usr/bin/pympress", line 33, in <module>
    sys.exit(load_entry_point('pympress==1.5.3', 'gui_scripts', 'pympress')())
  File "/usr/bin/pympress", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pympress/__main__.py", line 94, in <module>
    from pympress import extras, document, ui
  File "/usr/lib/python3.9/site-packages/pympress/ui.py", line 52, in <module>
    class UI(builder.Builder):
  File "/usr/lib/python3.9/site-packages/pympress/ui.py", line 126, in UI
    config = config.Config()
  File "/usr/lib/python3.9/site-packages/pympress/config.py", line 156, in __init__
    config.load_window_layouts()
  File "/usr/lib/python3.9/site-packages/pympress/config.py", line 291, in load_window_layouts
    loaded_layout = layout_from_json(self.get('layout', layout_name))
  File "/usr/lib64/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'layout'

**Comment by Cimbali** [comment]
That's pretty surprising. Seems to be some issue finding a section in the config file, however the config is pre-populated with defaults to ensure all settings are always there even on a fresh install...

Is there any thing in the log file? It should be at `~/.cache/pympress.log`

Maybe a workaround is to copy [the default config](https://github.com/Cimbali/pympress/blob/master/pympress/share/defaults.conf) file to `~/.config/pympress`

**Comment by rikiheck** [comment]
I tried that. No luck.
The log file is the same as what I posted above.
I had it installed previously by some other method: It ended up in .local/. I can't now remember how it came to be there. I deleted all that and then re-installed from copr. Don't know if that is relevant.
I've removed the copr install and run setup.py install from a git checkout. Same problem.

**Comment by rikiheck** [comment]
OK, so it worked with a new user. I found a couple stale files lying around in .local/. Deleted those and now it works fine. Sorry for the noise.

**Comment by Cimbali** [comment]
Was one of the stale files the `defaults.conf`?

**Comment by rikiheck** [comment]
No, it was some file living in ~/.local/python3.X/site-packages/.../ that I hadn't deleted. I think that was being picked up instead of the newer one for some reason, so there was some weird incompatibility. I still can't recall how pympress got installed there.

**Comment by Cimbali** [comment]
Okay, well glad it's worked out. We'll reopen when someone knows how to reproduce.
