### ISSUE TITLE
Cannot play videos

### ISSUE THREAD

**Issue by SommerEngineering** [Cimbali/pympress#199]
### Environment
- Ubuntu 20.04
- Python 3.8.5

### Pympress
- Version 1.6.1
- Installation method: pip

### Expected behaviour
I updated Pympress from 1.5.x to 1.6.1. Afterwards, I opened a previous presentation to test v1.6.1. On some slides, I had videos embedded. I expected, that the videos start playing after clicking on.

### Steps to reproduce
- Open slides with videos that are known to have worked previously
- Navigate to a slide where a video is embedded
- Click on the video to start it
- Nothing happens

### Problem
Nothing happens. In the log file, issues related to video are logged (see below).

What is reported in pympress.log?\*

Does the problem still happen if you remove your config file?\*
(You can just move the config file to a different location to be able to restore it after testing)

--------------------------------------------------------------------------------------------------

```
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
WARNING:pympress.document:Pympress can not interpret annotation of type: <enum POPPLER_ANNOT_WIDGET of type Poppler.AnnotType> 
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e55b4a40 (pympress+media_overlays+gst_backend+GstOverlay at 0x281eb20)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e42253c0 (GtkDrawingArea at 0x198c8d0)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1eedbdb40 (pympress+media_overlays+gst_backend+GstOverlay at 0x270a870)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e4229640 (GtkDrawingArea at 0x198c9f0)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e55bc0c0 (pympress+media_overlays+gst_backend+GstOverlay at 0x2815230)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e423b500 (GtkDrawingArea at 0x198cb10)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e4237c00 (pympress+media_overlays+gst_backend+GstOverlay at 0x2804cd0)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e4240280 (GtkDrawingArea at 0x198cc30)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e4225640 (pympress+media_overlays+gst_backend+GstOverlay at 0x288c2b0)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e4233c40 (GtkDrawingArea at 0x198cd50)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e423e3c0 (pympress+media_overlays+gst_backend+GstOverlay at 0x36860d0)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e42269c0 (GtkDrawingArea at 0x198ce70)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e423ed40 (pympress+media_overlays+gst_backend+GstOverlay at 0x3695160)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e4247c00 (GtkDrawingArea at 0x198cf90)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e4246300 (pympress+media_overlays+gst_backend+GstOverlay at 0x37f16f0)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e4246840 (GtkDrawingArea at 0x36750f0)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e42470c0 (pympress+media_overlays+gst_backend+GstOverlay at 0x37fad70)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e423bcc0 (GtkDrawingArea at 0x3675210)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e423b940 (pympress+media_overlays+gst_backend+GstOverlay at 0x3814160)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e42482c0 (GtkDrawingArea at 0x3675330)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e4240040 (pympress+media_overlays+gst_backend+GstOverlay at 0x38265c0)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e41ce040 (GtkDrawingArea at 0x3675450)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
ERROR:pympress.builder:Can not reach target of signal <gst_backend.GstOverlay object at 0x7fd1e4248c80 (pympress+media_overlays+gst_backend+GstOverlay at 0x383d380)>.play_pause()
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 122, in get_callback_handler
    target = getattr(target, attr)
AttributeError: 'GstOverlay' object has no attribute 'play_pause'
CRITICAL:pympress.builder:Impossible to connect signal button-press-event from object <Gtk.DrawingArea object at 0x7fd1e41cf880 (GtkDrawingArea at 0x3675570)> to handler play_pause
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/builder.py", line 144, in signal_connector
    object.connect(signal_name, handler, *user_data)
TypeError: second argument must be callable
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/extras.py", line 398, in <lambda>
    GLib.idle_add(lambda: any(p.do_play() for p in self._media_overlays[media_id]))
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/extras.py", line 398, in <genexpr>
    GLib.idle_add(lambda: any(p.do_play() for p in self._media_overlays[media_id]))
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/media_overlays/gst_backend.py", line 143, in do_play
    self.playbin.set_mute(self.muted)
AttributeError: 'GstPlayBin' object has no attribute 'set_mute'
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/extras.py", line 398, in <lambda>
    GLib.idle_add(lambda: any(p.do_play() for p in self._media_overlays[media_id]))
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/extras.py", line 398, in <genexpr>
    GLib.idle_add(lambda: any(p.do_play() for p in self._media_overlays[media_id]))
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/media_overlays/gst_backend.py", line 143, in do_play
    self.playbin.set_mute(self.muted)
AttributeError: 'GstPlayBin' object has no attribute 'set_mute'
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/media_overlays/gst_backend.py", line 161, in <lambda>
    GLib.idle_add(lambda *args: msg.src.set_window_handle(window.get_xid()))
AttributeError: 'GstPlaySink' object has no attribute 'set_window_handle'
ERROR:pympress.media_overlays.gst_backend:gst-resource-error-quark: Output window was closed (3) xvimagesink.c(554): gst_xv_image_sink_handle_xevents (): /GstPlayBin:playbin1/GstPlaySink:playsink/GstBin:vbin/GstXvImageSink:xvimagesink0
ERROR:pympress.media_overlays.gst_backend:gst-stream-error-quark: Internal data stream error. (1) qtdemux.c(6605): gst_qtdemux_loop (): /GstPlayBin:playbin1/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason error (-5)
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/thorsten/.local/lib/python3.8/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/thorsten/.local/lib/python3.8/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
```

**Comment by Cimbali** [comment]
It seems the beginning of the log is missing, but you appear to be using the Gstreamer backend, which is disabled by default.

Were you previously using VLC ? Can you check the values of `enabled` under the `[gst]` and `[vlc]` parts of the config file ?

**Comment by SommerEngineering** [comment]
Thanks @Cimbali for the fast support :slightly_smiling_face: Both, `[gst]` as well as `[vlc]` were `enabled = on`. `[gst]` was not further configured, though. I just changed `[gst]` to `off` and it works just fine. Thanks for developing and maintaining pympress. Keep the great work.
