### ISSUE TITLE
Playing movie15 videos embedded and autoplay does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by ojura** [Cimbali/pympress#213]
### Environment
Ubuntu 20.04
Python 3 (3.8.10)

### Pympress
System (apt-get), 1.6.4 (pip), 1.7.0b1 (built from source)

### Expected behaviour
Embedded video playback

### Steps to reproduce
Open presentation with embedded video which works in Okular and pympress on Windows

### Problem
No embedded video playback, large clickable "pin" icon is shown. Clicking opens the GNOME video player.

![image](https://user-images.githubusercontent.com/9062353/137791332-898d36ec-f125-477a-9876-d91c8b8ccece.png)

What is reported in pympress.log?\*
Nothing useful

Does the problem still happen if you remove your config file?\*
(You can just move the config file to a different location to be able to restore it after testing)
Yes

**Comment by Cimbali** [comment]
Hi @ojura, can you post your pympress.log? And also the `[vlc]` and `[gst]` in your config file?

**Comment by ojura** [comment]
Here's the log:
```
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/juraj/.local/lib/python3.8/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/juraj/.local/lib/python3.8/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.8.10 ; OS: Linux 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 ; Gtk 3.24.20 ; GLib 2.64.2 ; Poppler 0.86.1 cairo ; Cairo 1.16.0 , pycairo 1.16.2
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.16.2, VLC 3.0.9.2 Vetinari
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/juraj/.local/lib/python3.8/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/juraj/.local/lib/python3.8/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.8.10 ; OS: Linux 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 ; Gtk 3.24.20 ; GLib 2.64.2 ; Poppler 0.86.1 cairo ; Cairo 1.16.0 , pycairo 1.16.2
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.16.2, VLC 3.0.9.2 Vetinari
```

I haven't modified the config from the defaults:
```
[content]
xalign = 0.5
yalign = 0.5
geometry = 1920x1200+0+0
start_blanked = off
start_fullscreen = on
white_blanking = off

[presenter]
geometry = 1021x600+2402+727
start_fullscreen = off
pointer = red
pointer_mode = manual
show_bigbuttons = off
show_annotations = off
scroll_number = off
slide_ratio = 0.75

[layout]
plain = {
	    "resizeable": true,
	    "proportions": [
	        0.6699314397649363,
	        0.3300685602350637
	    ],
	    "orientation": "horizontal",
	    "children": [
	        "current",
	        {
	            "resizeable": true,
	            "proportions": [
	                0.55,
	                0.44999999999999996
	            ],
	            "orientation": "vertical",
	            "children": [
	                "next",
	                "annotations"
	            ]
	        }
	    ]
	}
highlight_tools = vertical
highlight = {
	    "resizeable": true,
	    "orientation": "horizontal",
	    "children": [
	        "highlight",
	        {
	            "resizeable": true,
	            "orientation": "vertical",
	            "children": [
	                "next",
	                "annotations"
	            ],
	            "proportions": [
	                0.55,
	                0.45
	            ]
	        }
	    ],
	    "proportions": [
	        0.67,
	        0.33
	    ]
	}
notes = {
	    "resizeable": true,
	    "children": [
	        "notes",
	        {
	            "resizeable": false,
	            "children": [
	                "current",
	                "next"
	            ],
	            "orientation": "vertical"
	        }
	    ],
	    "proportions": [
	        0.6,
	        0.4
	    ],
	    "orientation": "horizontal"
	}
note_pages = {
	    "resizeable": true,
	    "children": [
	        "notes",
	        {
	            "resizeable": false,
	            "children": [
	                "next",
	                "annotations"
	            ],
	            "orientation": "vertical"
	        }
	    ],
	    "proportions": [
	        0.6,
	        0.4
	    ],
	    "orientation": "horizontal"
	}

[notes position]
horizontal = right
vertical = bottom

[cache]
maxpages = 200

[highlight]
color_1 = rgba(255,255,0,0.5)
width_1 = 90
color_2 = rgba(128,255,0,0.5)
width_2 = 90
color_3 = rgba(255,0,128,0.5)
width_3 = 90
color_4 = rgba(48,48,255,0.5)
width_4 = 90
color_5 = rgb(239,41,41)
width_5 = 5
color_6 = rgb(0,96,255)
width_6 = 5
color_7 = rgb(0,187,0)
width_7 = 5
color_8 = rgb(0,0,0)
width_8 = 5
color_9 = rgba(255,0,0,1.)
width_9 = 8
active_pen = 9
mode = single-page

[gst]
enabled = off
init_options = 
mime_types = 

[vlc]
enabled = on
init_options = --no-video-title-show,--no-xlib
mime_types = 

[shortcuts]
next-page = Right Down Page_Down space
prev-page = Left Up Page_Up
first-page = Home
last-page = End
next-label = <ctrl>Right <ctrl>Down <ctrl>Page_Down <ctrl>space
prev-label = <ctrl>Left <ctrl>Up <ctrl>Page_Up
hist-back = <alt>Left
hist-forward = <alt>Right
goto-page = g
jumpto-label = j
content-fullscreen = F11 f F5 <ctrl>l
presenter-fullscreen = <ctrl>f
zoom = z
unzoom = u
notes-mode = n
annotations = a
highlight = h
swap-screens = s
blank-screen = b
quit = q
validate-input = Return KP_Enter
cancel-input = Escape
pick-file = o
close-file = <ctrl>w
pointer-mode::toggle = l
pause-timer = p Pause
reset-timer = r
edit-talk-time = t
timing-report = 
highlight-undo = <ctrl>z
highlight-redo = <ctrl>r
highlight-use-pen::1 = 1
highlight-use-pen::2 = 2
highlight-use-pen::3 = 3
highlight-use-pen::4 = 4
highlight-use-pen::5 = 5
highlight-use-pen::6 = 6
highlight-use-pen::7 = 7
highlight-use-pen::8 = 8
highlight-use-pen::9 = 9
highlight-use-pen::eraser = 0
highlight-clear = 

```

**Comment by Cimbali** [comment]
In my pympress (1.7 beta) the video you attached plays automatically on Linux. Are you sure you’re actually running the 1.7.0b1 with all the versions you installed? (Look in Help > About.)

I think you can’t access it by clicking with `attach=true` because the attachment is on top in z-index, but auto-playing solves that because the video is rendered on top of the other annotation.

**Comment by ojura** [comment]
Thanks for the prompt responses!
