### ISSUE TITLE
Installing on M1 ARM Mac

### ISSUE THREAD

**Issue by jjay0258** [Cimbali/pympress#220]
**Describe the bug**
Can not install using brew on ARM Mac. 
Tried the following:
1. brew install pympress
2. brew install --build-from-source pympress
3. arch x86_64 brew install pympress
4. arch x86_64 brew install --build-from-source pympress

I managed to install it by building from source on both arm64 and x86_64 architectures, but neither of them starts. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/28506530/139636545-10594aea-0bad-44a1-8782-7f7e76158468.png">

<img width="453" alt="image" src="https://user-images.githubusercontent.com/28506530/139636582-2c72c88b-c601-46dd-96c4-e780c0771217.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/28506530/139636626-18c80c9a-a31b-4095-84eb-fc55d6ef89b2.png">

**Environment (please complete the following information):**
 - OS: macOS 11.6
 - Python version: 3.9.6
 - Pympress version: 1.6.4
 - Installation method: source and brew

**Debug information (see below for file locations)**
 - What is reported in pympress.log? -> **see below**
 - Does the problem still happen if you remove your config file? **Yes**

log:
`DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/pympress/util.py", line 78, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/opt/homebrew/Cellar/pympress/1.6.4/libexec/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.6.4 ; Python: 3.9.7 ; OS: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.10.0 cairo ; Cairo 1.16.0 , pycairo 1.20.1
`

**Comment by Cimbali** [comment]
Thanks for reporting @jjay0258. This seems to be the same as #190. Unfortunately this is a bug in pygobject on which we depend, see their issues [455](https://gitlab.gnome.org/GNOME/pygobject/-/issues/455) and [489](https://gitlab.gnome.org/GNOME/pygobject/-/issues/489).

Apparently the issue is due to a libffi closure function in gobject introspections (`g_callable_info_prepare_closure`) returning the address of a function’s executable code, instead of the address of a closure which contains a pointer to that code. These used to point to the same place but not anymore, which if I read correctly is to solve a security issue − to avoid having executable code in the middle of your stack, that prepares registers for the enclosed function. This piece of code, called a static trampoline, is now located somewhere else, which means it’s a problem the wrong address is returned.

However this « new » behaviour seems to be new in Linux when upgrading from libffi 3.3 to 3.4, but possibly was always the case on macOS with M1 architectures. The flag only to enable static trampoline seems to only ever be set on Linux:

https://github.com/libffi/libffi/blob/0f2dd369cd5edcefad29b3fca4e1d08cb34f8f19/configure.ac#L376-L378

Unfortunately this means that we need to wait for pygobject’s [MR 283](https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/283) to be merged, which according to milestones and their release dates should be in next February (if nothing else changes).
