### ISSUE TITLE
"Notes mode" not working

### ISSUE THREAD

**Issue by mroavi** [Cimbali/pympress#234]
**Describe the bug**
The "Notes mode" is not working. When enabled, instead of showing notes, half of the slide is displayed and the other half is displayed in the "current slide" preview. See image below:

![pympress-notes-bug](https://user-images.githubusercontent.com/19517248/145121057-de010c66-17bb-4b52-83d9-0b2a63c2aa8f.png)

**To Reproduce**
1. Generate a beamer presentation with:
```
\note[itemize]{
\item point 1
\item point 2
}
```
within two frames.
2. Open the pdf with `pympress main.pdf`
3. Start "Notes mode"

**Expected behavior**
The notes should be displayed.

**Environment (please complete the following information):**
Pympress: 1.7.1 ;
Python: 3.9.7 ;
OS: Linux 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 ;
Gtk 3.24.30 ;
GLib 2.70.0 ;
Poppler 21.11.0 cairo ;
Cairo 1.17.4 , pycairo 1.20.1

Installation method: pip install pympress

**Debug information (see below for file locations)**
```
DEBUG:pympress.util:Failed to get git describe output
Traceback (most recent call last):
  File "/home/mroavi/.local/lib/python3.9/site-packages/pympress/util.py", line 72, in get_pympress_meta
    git_version = subprocess.check_output(command, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir=/home/mroavi/.local/lib/python3.9/site-packages/.git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
INFO:pympress.app:Pympress: 1.7.1 ; Python: 3.9.7 ; OS: Linux 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 ; Gtk 3.24.30 ; GLib 2.70.0 ; Poppler 21.11.0 cairo ; Cairo 1.17.4 , pycairo 1.20.1
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer 1.18.5, VLC 3.0.16 Vetinari
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling
WARNING:pympress.util:Should not require hard enable/disable screensaver on Linux
ERROR:pympress.scribble:Error creating highlight cache
Traceback (most recent call last):
  File "/home/mroavi/.local/lib/python3.9/site-packages/pympress/scribble.py", line 340, in reset_scribble_cache
    self.scribble_cache = window.create_similar_image_surface(cairo.Format.ARGB32, ww, wh, scale)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 155, in __getattr__
    setattr(wrapper, value_name, wrapper(value_info.get_value()))
ValueError: invalid enum value: 5
```

 - Does the problem still happen if you remove your config file?
Yes.

**Comment by mroavi** [comment]
This is not a bug in pympress. It was a problem with my understanding of how to use beamer notes and pympress.

The problem was that I was not setting:
```tex
\setbeameroption{show notes on second screen=right} % Both
```
in the preamble of my presentation and that I was inserting notes outside of a frame (not sure if this last point is indeed a problem). This did work for me:
```tex
\begin{frame}

  \begin{itemize}
  \item Here are
  \item some very boring bullets
  \item about nothing.
  \end{itemize}
  
  \note[item]{Note that this slide is boring.}

  \note[item]{Observe that there are no actual bullets here.}

  \note[item]{Future work: add another bullet.}
\end{frame}
```
Here is a link to the gist with the complete demo breamer presentation: https://gist.github.com/andrejbauer/ac361549ac2186be0cdb
