### ISSUE TITLE
Wrongly sized slides in deck overview

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/pympress#272]
**Describe the bug**
In deck overview, slides appear 1/4 of the size they should have

**To Reproduce**
Open deck view on a single-page A4 PDF on Windows

**Expected behavior**
Well sized pages

**Screenshots**
Without notes mode:
![image](https://user-images.githubusercontent.com/6126377/223588887-7b131d1f-d6fa-4825-a18f-068b241bc9ab.png)

With notes mode:
![image](https://user-images.githubusercontent.com/6126377/223588327-4333d52a-d442-4370-acd9-96920cf09d32.png)

**Environment (please complete the following information):**
 - OS: Windows 10 N
 - Python version: 3.10.10
 - Pympress version: 1.8.0b
 - Installation method: installer

**Debug information (see below for file locations)**

log contents:
```
INFO:pympress.app:Pympress: 1.8.0 ; Python: 3.10.10 ; OS: Windows 10 10.0.19044 ; Gtk 3.24.37 ; GLib 2.74.0 ; Poppler 23.02.0 cairo ; Cairo 1.17.8 , pycairo 1.23.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC 3.0.17.4 Vetinari
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling
ERROR:pympress.scribble:Error creating highlight cache
Traceback (most recent call last):
  File "D:/a/pympress/pympress/pympress/scribble.py", line 412, in reset_scribble_cache
  File "D:/a/_temp/msys64/mingw64/lib/python3.10/site-packages/gi/module.py", line 155, in __getattr__
ValueError: invalid enum value: 5
```

**Comment by Cimbali** [comment]
Can reproduce on Linux with single-page documents of various aspect ratios.
