### ISSUE TITLE
Undo Clears Slide

### ISSUE THREAD

**Issue by Lazaro10e0** [Cimbali/pympress#292]
**Describe the bug**
Sometimes when I do Ctrl+Z it clears the whole slide.

**To Reproduce**
I don't know when it happens, just that sometimes the Undo works fine and sometimes it clears the whole slide...

**Expected behavior**
Only one undo.

**Environment (please complete the following information):**
 - OS: W10
 - Python version: Python 3.10.11
 - Pympress version: 1.8.3b
 - Installation method: MSI file

**Comment by Cimbali** [comment]
Is there anything in the log file? It should be in `%LOCALAPPDATA%\pympress.log` (usually `C:\Users\<username>\AppData\pympress.log`)

**Comment by Lazaro10e0** [comment]
[undo_clears_slide.txt](https://github.com/Cimbali/pympress/files/11833404/undo_clears_slide.txt)
It just happened. I attach the log file.

**Comment by Cimbali** [comment]
Thanks! This is the bit corresponding to the last execution:
```
INFO:pympress.app:Pympress: 1.8.3b ; Python: 3.10.11 ; OS: Windows 10 10.0.19045 ; Gtk 3.24.38 ; GLib 2.76.1 ; Poppler 23.03.0 cairo ; Cairo 1.17.8 , pycairo 1.23.0
INFO:pympress.extras:Media support: GdkPixbuf gif player, GStreamer not available, VLC not available
WARNING:pympress.ui:Gtk.Application.inhibit failed preventing screensaver, trying hard disabling
CRITICAL:__main__:Uncaught exception:
Traceback (most recent call last):
  File "D:/a/pympress/pympress/pympress/app.py", line 242, in do_shutdown
  File "D:/a/pympress/pympress/pympress/ui.py", line 727, in cleanup
  File "D:/a/pympress/pympress/pympress/scribble.py", line 775, in disable_scribbling
AttributeError: 'NoneType' object has no attribute 'set_event_compression'
```

**Comment by Cimbali** [comment]
Can you click undo further? What happens if you try to redo?
