### ISSUE TITLE
TypeError: 'gi._gi.GPropsIter' object is not iterable

### ISSUE THREAD

**Issue by carlosal1015** [Cimbali/pympress#330]
**Describe the bug**

When I start the program with python 3.13 we have the following error

```python
$ pympress 
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pympress/app.py", line 164, in do_activate
    self.gui = ui.UI(self, self.config)
               ~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pympress/ui.py", line 212, in __init__
    self.load_ui('presenter')
    ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pympress/builder.py", line 186, in load_ui
    self.__translate_widget_strings(obj)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/site-packages/pympress/builder.py", line 79, in __translate_widget_strings
    for str_prop in (prop.name for prop in a_widget.props if prop.value_type == GObject.TYPE_STRING):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pympress/builder.py", line 79, in <genexpr>
    for str_prop in (prop.name for prop in a_widget.props if prop.value_type == GObject.TYPE_STRING):
                                           ^^^^^^^^^^^^^^
TypeError: 'gi._gi.GPropsIter' object is not iterable
```

**To Reproduce**
1. Start pympress from terminal.

**Expected behavior**

Open the gui.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.13.1
 - Pympress version: 1.8.5-2
 - Installation method: https://aur.archlinux.org/packages/python-pympress

**Comment by Cimbali** [comment]
The properties iterator is not iterable… that’s interesting. Can you share the 2 first lines of your log file? It should give all the detailed versions of dependencies – Gtk etc.

**Comment by carlosal1015** [comment]
I am not sure where is located the log file, over ~/.config no directory called pympress.
```
➜  ~ pacman -Qi python-pympress 
Name            : python-pympress
Version         : 1.8.5-2
Description     : Simple and powerful dual-screen PDF reader designed for presentations
Architecture    : any
URL             : https://github.com/Cimbali/pympress
Licenses        : GPL-2.0-or-later
Groups          : None
Provides        : None
Depends On      : poppler-glib  gtk3  python-cairo  gdk-pixbuf2  python-gobject  gobject-introspection  python-watchdog  perl-x11-protocol  perl-net-dbus
Optional Deps   : vlc: for playing videos [installed]
                  python-vlc: for playing videos
                  gstreamer: for playing videos [installed]
                  gst-plugin-gtk: for playing videos
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 823.82 KiB
Packager        : Unknown Packager
Build Date      : Sun 22 Dec 2024 03:40:14 PM -05
Install Date    : Sun 22 Dec 2024 04:28:39 PM -05
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

- [`poppler-glib 24.11.0-2`](https://archlinux.org/packages/extra/x86_64/poppler-glib/files)
- [`gtk3 1:3.24.43-4`](https://archlinux.org/packages/extra/x86_64/gtk3/files)
- [`python-cairo 1.27.0-2`](https://archlinux.org/packages/extra/x86_64/python-cairo/files)
- [`gdk-pixbuf2 2.42.12-2`](https://archlinux.org/packages/extra/x86_64/gdk-pixbuf2/files)
- [`python-gobject 3.50.0-2`](https://archlinux.org/packages/extra/x86_64/python-gobject/files)
- [`gobject-introspection 1.82.0-2`](https://archlinux.org/packages/extra/x86_64/gobject-introspection/files)
- [`python-watchdog 3.0.0-2`](https://archlinux.org/packages/extra/any/python-watchdog/files)
- [`perl-x11-protocol 0.56-16`](https://archlinux.org/packages/extra/any/perl-x11-protocol/files)
- [`perl-net-dbus 1.2.0-7`](https://archlinux.org/packages/extra/x86_64/perl-net-dbus/files)
- [`vlc 3.0.21-9`](https://archlinux.org/packages/extra/x86_64/vlc/files)
- [`gstreamer 1.24.10-2`](https://archlinux.org/packages/extra/x86_64/gstreamer/files)
```

**Comment by Cimbali** [comment]
Logs should be under `~/.cache` but you've already given all the info I was looking for

**Comment by carlosal1015** [comment]
Nice, but in my case over `~/.cache` no one directory called pympress.

**Comment by carlosal1015** [comment]
> Logs should be under `~/.cache` but you've already given all the info I was looking for. Will try to reproduce

With docker is easy to reproduce
```
$ docker run -it --rm archlinux:base-devel
useradd -l -md /home/aur -s /bin/bash aur
passwd -d aur
echo 'aur ALL=(ALL) ALL' > /etc/sudoers.d/aur
pacman -Syu git xorg-server-xvfb
su aur
cd ~
git clone https://aur.archlinux.org/python-pympress.git
cd python-pympress
makepkg --noconfirm -si
sudo Xvfb :5 &
DISPLAY=:5 pympress
cat ~/.cache/pympress.log
```

**Comment by Cimbali** [comment]
Ok this is technically a bug in `GPropsIter` which is missing its required `__iter__` function (it only has `__next__`). I’d prefer to see it fixed upstream rather than add a workaround in code, as that would also not be guaranteed to be future-proof. 

Temporary fixes are:
- use python ≤ 3.12
- change line 79 in `builder.py` as follows:
  ```patch
  --- i/pympress/builder.py
  +++ w/pympress/builder.py
  @@ -76,7 +76,7 @@ class Builder(Gtk.Builder):
           Args:
               a_widget (:class:`~GObject.Object`): an object built by the builder, usually a widget
           """
  -        for str_prop in (prop.name for prop in a_widget.props if prop.value_type == GObject.TYPE_STRING):
  +        for str_prop in (prop.name for prop in list(a_widget.props) if prop.value_type == GObject.TYPE_STRING):
               try:
                   str_val = getattr(a_widget.props, str_prop)
                   if str_val:
    ```
(i.e. don’t rely on the conversion to an iterator.)

This patch can be added in AUR or wherever people use python 3.13 early. If I see no movement to fix the issue in GObject I’ll merge this in main.

**Comment by carlosal1015** [comment]
Thanks, just in time for my talk today 😄

It is working and was patched in [AUR](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-pympress&id=ed02bcfbf0c815c0f96a7d5b61e447e0293f832c).
![image](https://github.com/user-attachments/assets/04bafac2-be5c-4f34-8467-26ac3ced44f4)

**Comment by Cimbali** [comment]
Great! Let's keep this open for now to not forget about it though.

**Comment by jobrachem** [comment]
I ran into the same issue today on MacOS. I used the temporary fix pointed out by @Cimbali, i.e. changed the affected line in `builder.py`. Works for now, thanks!

**Comment by Cimbali** [comment]
A [fix was merged](https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/392) in pygobject, let’s monitor releases.

**Comment by Titikomba** [comment]
Hi, quick update:
- The 3.51 version of [pygobject](https://gitlab.gnome.org/GNOME/pygobject/-/releases) was released.
- People are working on the pip recipe [see here](https://pypi.org/project/PyGObject/3.51.0.dev0/#history).
- Haven't seen issues/merge requests on brew atm.

**Comment by Cimbali** [comment]
I’m a bit confused as to whether the fix is in 3.51.0 or if we have to wait for the next one.

**Comment by GrafKnusprig** [comment]
Quick Update:
I'm on mac an installed pympress via homebrew. I also had the issue and did the fix on line 79 in the builder.py. It's working for now. Didn't have to change the python version tough.

**Comment by Cimbali** [comment]
Hi @GrafKnusprig thanks for the update. I’ve updated the post to clarify these are 2 different options, both of which should fix the issue. I’ve also just tested pygobject 3.51 which seems to fix the problem, so when it’s released we’ll be able to close this issue.

**Comment by Cimbali** [comment]
Closing this as complete now that fixed pygobject is out (current version is 3.52.3). The bug may still appear if you run both:
- python ≥ 3.13
- pygobject < 3.51
In which case the best fix is to update pygobject. If that is not immediately doable, refer to [workarounds listed here](https://github.com/Cimbali/pympress/issues/330#issuecomment-2562515602)
