### ISSUE TITLE
embedded video disabled on Windows 10 (binary installer with VLC)

### ISSUE THREAD

**Issue by r5r3** [Cimbali/pympress#39]
From the logfile:

```
ERROR:pympress.ui:video support is disabled
Traceback (most recent call last):
  File "C:\Users\bscuser\Documents\pympress\pympress\ui.py", line 66, in <module>
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
  File "c:\Python\64-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
  File "C:\Users\bscuser\Documents\pympress\pympress\vlcvideo.py", line 56, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by Cimbali** [comment]
I didn't close this yet because I don't know whether VLC will work as intended without adding its plugin path to $PATH.

**Comment by Cimbali** [comment]
After testing, seems like it works fine.
