### ISSUE TITLE
AttributeError: 'Overlay' object has no attribute 'reorder_overlay'

### ISSUE THREAD

**Issue by moi90** [Cimbali/pympress#5]
```
pympress document.pdf 
Traceback (most recent call last):
  File "/home/moi/.local/bin/pympress", line 9, in <module>
    load_entry_point('pympress==0.6', 'gui_scripts', 'pympress')()
  File "/home/moi/.local/lib/python3.4/site-packages/pympress/__main__.py", line 86, in main
    ui = pympress.ui.UI(name, ett)
  File "/home/moi/.local/lib/python3.4/site-packages/pympress/ui.py", line 275, in __init__
    self.setup_scribbling()
  File "/home/moi/.local/lib/python3.4/site-packages/pympress/ui.py", line 1897, in setup_scribbling
    self.c_overlay.reorder_overlay(self.scribble_c_eb, 1)
AttributeError: 'Overlay' object has no attribute 'reorder_overlay'
```

Installed via python3 -m pip

**Comment by Cimbali** [comment]
I have a little trouble seeing what could cause this. In particular, [Gtk.Overlay.reorder_overlay seems to have always existed,](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Overlay.html#Gtk.Overlay.reorder_overlay) not to be an addition in a later version.

I see you're running python 3.4, but could you be so kind as to complete the following information:
- platform (OS, version)
- gtk version
- pygobject bindings version
- pympress version (git revision if possible)

**Comment by Cimbali** [comment]
Impossible to reproduce.
