### ISSUE TITLE
Option -t raises exception

### ISSUE THREAD

**Issue by polaksta** [Cimbali/pympress#50]
# Environment
- Linux Ubuntu 17.10
- Python 3.6.3 

# Pympress
- 1.1.1
- pip

# Expected behaviour 
I try to specify the duration of the presentation using '-t' option or 't' key. When '-t' is used, exception occurs. If I run without the abovementioned option everything is OK. But if I press 't' and I tray to set the duration, e.g., 90:00, then "Time elapsed" value does not change, and after closing the program displays: 

```
(pympress3:1978): Gtk-WARNING **: Allocating size to GtkPaned 0x1a95f90 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1483866739 (0x58720273)
 at -e line 15.
Traceback (most recent call last):
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 256, in update_time
    self.label_colorer.update_time_color(self.ett.est_time - self.delta)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 135, in update_time_color
    color_spec = '* {color: {}}'.format(color.to_string())
KeyError: 'color'
```

# Steps to reproduce
What are you doing? 
Running pympress with -t / --talk_time
```
$ pympress3 -t 90:00 js.pdf
$ pympress3 --talk-time=90:00 js.pdf
```
# Problem

When I run pympress without '-t' everything is OK. But when I run it as follows:
pympress3 -t 90:00 js.pdf it displays:
```
(pympress3:32688): Gtk-WARNING **: Allocating size to GtkPaned 0x30abf90 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/home/polak/.local/bin/pympress3", line 11, in <module>
    load_entry_point('pympress==1.1.1', 'gui_scripts', 'pympress3')()
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/__main__.py", line 113, in main
    gui = ui.UI(ett, name)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/ui.py", line 221, in __init__
    self.swap_document(docpath)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/ui.py", line 501, in swap_document
    self.talk_time.reset_timer()
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 233, in reset_timer
    self.update_time()
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 256, in update_time
    self.label_colorer.update_time_color(self.ett.est_time - self.delta)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 135, in update_time_color
    color_spec = '* {color: {}}'.format(color.to_string())
KeyError: 'color'
```
\-----------------------------------------------------------------
```
$ cat pympress.log 
CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "/home/polak/.local/bin/pympress3", line 11, in <module>
    load_entry_point('pympress==1.1.1', 'gui_scripts', 'pympress3')()
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/__main__.py", line 113, in main
    gui = ui.UI(ett, name)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/ui.py", line 221, in __init__
    self.swap_document(docpath)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/ui.py", line 501, in swap_document
    self.talk_time.reset_timer()
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 233, in reset_timer
    self.update_time()
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 256, in update_time
    self.label_colorer.update_time_color(self.ett.est_time - self.delta)
  File "/home/polak/.local/lib/python3.6/site-packages/pympress/talk_time.py", line 135, in update_time_color
    color_spec = '* {color: {}}'.format(color.to_string())
KeyError: 'color'
```

**Comment by Cimbali** [comment]
Sounds like a straightforward silly error, the string should be `'* {{color: {}}}'`. I don't know how this didn't show up before.

**Comment by Cimbali** [comment]
Closed by 5c52a70

**Comment by polaksta** [comment]
After upgrade to version 1.1.2 everything is OK - option '-t' works now. Thanks.

**Comment by mgmax** [comment]
@Cimbali could you please upload a new Windows build? Thanks in advance!
