### ISSUE TITLE
Gtk+ version requirement to high for Linux Mint 18.3 – error on slides with videos

### ISSUE THREAD

**Issue by complanar** [Cimbali/pympress#51]
The file vlcvideo.glade triggers an error because of unsatisfied requirements. Videos could not be played.

# Environment
- Linux Mint 18.3
- Python version 3.5

# Pympress
- 1.1.2
- Installation method: source

# Expected behaviour 
No error :-)

# Steps to reproduce
With Gtk+ version 3.18 installed pympress throws an error when changing to a slide with video:

    Traceback (most recent call last):
      File "/home/teichert/Development/pympress/pympress/ui.py", line 812, in on_navigation
        self.doc.goto_next()
      File "/home/teichert/Development/pympress/pympress/document.py", line 678, in goto_next
        self.goto(self.cur_page + 1)
      File "/home/teichert/Development/pympress/pympress/document.py", line 666, in goto
        self._do_page_change(number)
      File "/home/teichert/Development/pympress/pympress/document.py", line 651, in_do_page_change
        self.page_change()
      File "/home/teichert/Development/pympress/pympress/ui.py", line 706, in on_page_change
        self.medias.replace_media_overlays(self.doc.current_page())
      File "/home/teichert/Development/pympress/pympress/extras.py", line 178, in replace_media_overlays
        v_da_c = vlcvideo.VLCVideo(self.c_overlay, show_controls, relative_margins, get_curryfied_callback)
      File "/home/teichert/Development/pympress/pympress/vlcvideo.py", line 135, in __init__
        self.load_ui('vlcvideo')
      File "/home/teichert/Development/pympress/pympress/builder.py", line 183, in load_ui
        self.add_from_file(util.get_ui_resource_file(resource_name))
    GLib.Error: gtk-builder-error-quark: /home/teichert/Development/pympress/pympress/share/xml/vlcvideo.glade:5:1 Required gtk+ version 3.20, current version is 3.18 (7)

# Problem
The file `pympress/share/xml/vlcvideo.glade` reads `<requires lib="gtk+" version="3.20"/>` at line 4.
I could remove the error by changing to `version="3.2"` as found in the other glade files.
Everything seemed to worke fine after that.

Is there any specific reason for requiring v 3.20 or was this simply inserted by the development software itself?

**Comment by Cimbali** [comment]
Definitely a bug, 3.2 is what was intended. I think I fully created the file with Glade so you might be right, it might have been inserted automatically.
