### ISSUE TITLE
GLib.Error: gtk-builder-error-quark: Invalid property: GtkPaned.wide_handle on line 464 (11)

### ISSUE THREAD

**Issue by HYChou0515** [Cimbali/pympress#79]
Dependencies installed but cannot run pympress.

# Environment
- Operating system and version
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

- Python version
anaconda python 2.7

- Pympress
 v1.2.0, newest from pip

- Dependencies
  poppler  0.67.0
  gtk3  3.14.15
  cairo  1.14.12
  gdk-pixbuf  2.32.2
  pygobject 3.28.2

# Steps to reproduce
create new conda environment and activate it, install pympress by pip.
```
$ conda create -n py27 python=2.7 anaconda
$ source activate py27
$ python -m pip install pympress
 Collecting pympress
   Using cached https://files.pythonhosted.org/packages/b0/5c/70c9c50529d466d70b8770f586f544de43189921b13742e4808f90fc5eb5/pympress-1.2.0-py2.py3-none-any.whl
 Requirement already satisfied: python-vlc in /home/hychou/.local/lib/python2.7/site-packages (from pympress) (3.0.102)
 Installing collected packages: pympress
 Successfully installed pympress-1.2.0
```
install and check dependencies:
```
$ conda install -n py27 -c conda-forge poppler
$ conda install -n py27 -c pkgw/label/superseded gtk3 
$ conda install -n py27 -c conda-forge pygobject 
$ conda list -n py27

# packages in environment at /home/hychou/anaconda3/envs/py27:
#
anaconda                  custom           py27h4a00acb_0  
cairo                     1.14.12              he6fea26_5    conda-forge
cairo-gobject             1.12.18                       8    pkgw/label/superseded
gdk-pixbuf                2.32.2                        2    pkgw/label/superseded
gtk3                      3.14.15                       4    pkgw/label/superseded
pip                       18.0                     py27_1    conda-forge
poppler                   0.67.0               h4d7e492_3    conda-forge
poppler-data              0.4.9                         0    conda-forge
pycairo                   1.16.3           py27h4d1f301_0    conda-forge
pygobject                 3.28.3           py27h23641be_0    conda-forge
pympress                  1.2.0                     <pip>
python                    2.7.15               h9fef7bc_0    conda-forge
...
```

run pympress:
```
pympress

Traceback (most recent call last):
  File "/home/hychou/anaconda3/envs/py27/bin/pympress", line 11, in <module>
    sys.exit(main())
  File "/home/hychou/anaconda3/envs/py27/lib/python2.7/site-packages/pympress/__main__.py", line 113, in main
    gui = ui.UI(ett, name)
  File "/home/hychou/anaconda3/envs/py27/lib/python2.7/site-packages/pympress/ui.py", line 183, in __init__
    self.load_ui('presenter')
  File "/home/hychou/anaconda3/envs/py27/lib/python2.7/site-packages/pympress/builder.py", line 193, in load_ui
    self.add_from_file(util.get_ui_resource_file(resource_name))
GLib.Error: gtk-builder-error-quark: Invalid property: GtkPaned.wide_handle on line 464 (11)
```

# Problem
Pympress crashes want I attempt to run. The contents of pympress.log are:
```
ERROR:pympress.config:Invalid layout
Traceback (most recent call last):
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/config.py", line 271, in load_window_layouts
    self.layout[layout_name] = layout_from_json(self.get('layout', layout_name))
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/config.py", line 74, in layout_from_json
    raise ValueError('No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.')
ValueError: No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.

ERROR:pympress.config:Invalid layout
Traceback (most recent call last):
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/config.py", line 271, in load_window_layouts
    self.layout[layout_name] = layout_from_json(self.get('layout', layout_name))
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/config.py", line 74, in layout_from_json
    raise ValueError('No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.')
ValueError: No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.

ERROR:pympress.config:Invalid layout
Traceback (most recent call last):
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/config.py", line 271, in load_window_layouts
    self.layout[layout_name] = layout_from_json(self.get('layout', layout_name))
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/config.py", line 74, in layout_from_json
    raise ValueError('No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.')
ValueError: No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.

CRITICAL:pympress.__main__:Uncaught exception:
Traceback (most recent call last):
  File "/home/hychou/anaconda3/envs/env_python27/bin/pympress", line 11, in <module>
    sys.exit(main())
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/__main__.py", line 113, in main
    gui = ui.UI(ett, name)
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/ui.py", line 183, in __init__
    self.load_ui('presenter')
  File "/home/hychou/.local/lib/python2.7/site-packages/pympress/builder.py", line 193, in load_ui
    self.add_from_file(util.get_ui_resource_file(resource_name))
Error: gtk-builder-error-quark: Invalid property: GtkPaned.wide_handle on line 464 (11)
```

**Comment by Cimbali** [comment]
The issue seems to be that the `wide_handle` property did not exist before v3.16, while you're running gtk v3.14.15 which is from July 2015. If you update your system the error should go away.

In the mean time I'll remove this dependency so we keep supporting old machines.

**Comment by Cimbali** [comment]
Try the following in your conda python to get the latest fix:
```
python -m pip install --upgrade git+https://github.com/Cimbali/pympress#egg=pympress
```

Alternately do that without the `--upgrade` for a fresh install.
