### ISSUE TITLE
ImportError for 'ui' using PIP package

### ISSUE THREAD

**Issue by FriedrichFroebel** [Cimbali/pympress#92]
### Environment

- Windows 8.1
- Python 3.4.4

### Pympress

- Version 1.2.1
- Installation method: pip

### Expected behaviour

The `pympress` package can be opened from the command line.

### Steps to reproduce

1. Open `cmd.exe`
2. Run `python34 -m pympress`

### Problem

An error is thrown:

```
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\pympress\__main__.py", line 52, in <module>
    from pympress import media_overlay, document, ui
  File "C:\Python34\lib\site-packages\pympress\ui.py", line 50, in <module>
    from pympress import __main__, document, surfacecache, util, pointer, scribble, config, builder, talk_time, extras, editable_label
  File "C:\Python34\lib\site-packages\pympress\__main__.py", line 52, in <module>
    from pympress import media_overlay, document, ui
ImportError: cannot import name 'ui'
```

When cloning the repository and checking out `v1.2.1` the same error is thrown. The `master` branch seems to work fine.

The log file is empty.

**Comment by Cimbali** [comment]
It's a circular import problem solved in aace60a. Thanks for reporting, I should release it to pip.
