### ISSUE TITLE
pympress exits with no errors when fast browsing slides

### ISSUE THREAD

**Issue by robertozanasi** [Cimbali/pympress#98]
# Environment
- Operating system and version: windows 10
- Python version: 2.7

# Pympress
- version: 1.3.1
- Installation method: pip

# Expected behaviour 
Browse through pdf file with page-up/page-down

# Steps to reproduce
After loading pdf file, I would like to browse fast through it 

# Problem
What's happening instead of what you are expecting?
pympress exits with no error messages. I have tried to increase the number of cached slides, but I can't find pympress.ini on my hard drive.

What is reported in pympress.log?

```
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "C:\Python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
ERROR:pympress.config:Invalid layout
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pympress\config.py", line 274, in load_window_layouts
    self.layout[layout_name] = layout_from_json(self.get('layout', layout_name))
  File "C:\Python27\lib\site-packages\pympress\config.py", line 81, in layout_from_json
    raise ValueError('No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.')
ValueError: No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.
ERROR:pympress.config:Invalid layout
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pympress\config.py", line 274, in load_window_layouts
    self.layout[layout_name] = layout_from_json(self.get('layout', layout_name))
  File "C:\Python27\lib\site-packages\pympress\config.py", line 81, in layout_from_json
    raise ValueError('No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.')
ValueError: No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.
ERROR:pympress.config:Invalid layout
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pympress\config.py", line 274, in load_window_layouts
    self.layout[layout_name] = layout_from_json(self.get('layout', layout_name))
  File "C:\Python27\lib\site-packages\pympress\config.py", line 81, in layout_from_json
    raise ValueError('No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.')
ValueError: No layout string passed. Ignore this error if you just upgraded pympress or reset your configuration file.
INFO:__main__:Pympress: 1.3.1 ; Python: 2.7.15 ; OS: Windows 10 ; Gtk 3.18.9 ; GLib  2.52.1 ; Poppler 0.54.0 cairo ; Cairo 1.15.2 , pycairo 0.12.0 ; Media: GtkImage gif player
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
```

**Comment by Cimbali** [comment]
Can you show  `python2 -m pip list` and if `enum34` is missing, install it and see if it fixes it?

**Comment by robertozanasi** [comment]
This is the output:    
    C:\Python27>python.exe -m pip list
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your 
    Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for 
    Python 2.7.
    Package    Version
    ---------- --------
    argh       0.26.2
    enum34     1.1.6
    pathtools  0.1.2
    pip        19.0.2
    pydbus     0.6.0
    pygobject  3.24.1
    pympress   1.3.1
    python-vlc 3.0.4106
    PyYAML     3.13
    setuptools 39.0.1
    watchdog   0.9.0

`enum34` was missing, without it I couldn't run pympress. After I installed it, I noticed the problem with fast browsing.

I installed gtk using PyGobjectWin32.

**Comment by Cimbali** [comment]
Can you try running with `GTK_DEBUG=modules GDK_DEBUG=draw pympress`  ? That should give us some info and hopefully tell us what happens.

Can you also try with `GDK_DEBUG=draw,nogl`,  `GDK_DEBUG=draw GDK_RENDERING=image`, and   `GDK_DEBUG=draw GDK_RENDERING=recording`? Those will degrade drawing perormance, maybe cause flickering, but the goal is to see if it prevents crashes.

**Comment by robertozanasi** [comment]
Just to be sure: I had to set windows environmental variables `GTK_DEBUG` and `GDK_DEBUG`, right? This is the log file:

```
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "c:\python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "c:\python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
INFO:pympress.__main__:Pympress: 1.3.1 ; Python: 2.7.15 ; OS: Windows 10 ; Gtk 3.18.9 ; GLib  2.52.1 ; Poppler 0.54.0 cairo ; Cairo 1.15.2 , pycairo 0.12.0 ; Media: GtkImage gif player
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "c:\python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "c:\python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
INFO:pympress.__main__:Pympress: 1.3.1 ; Python: 2.7.15 ; OS: Windows 10 ; Gtk 3.18.9 ; GLib  2.52.1 ; Poppler 0.54.0 cairo ; Cairo 1.15.2 , pycairo 0.12.0 ; Media: GtkImage gif player
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "c:\python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "c:\python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "c:\python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "c:\python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "c:\python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "c:\python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
INFO:pympress.__main__:Pympress: 1.3.1 ; Python: 2.7.15 ; OS: Windows 10 ; Gtk 3.18.9 ; GLib  2.52.1 ; Poppler 0.54.0 cairo ; Cairo 1.15.2 , pycairo 0.12.0 ; Media: GtkImage gif player
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor
ERROR:pympress.media_overlay:Video support using VLC is disabled.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pympress\media_overlay.py", line 528, in <module>
    import vlc
  File "c:\python27\lib\site-packages\vlc.py", line 203, in <module>
    dll, plugin_path  = find_lib()
  File "c:\python27\lib\site-packages\vlc.py", line 173, in find_lib
    dll = ctypes.CDLL(libname)
  File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] Impossibile trovare il modulo specificato
INFO:pympress.__main__:Pympress: 1.3.1 ; Python: 2.7.15 ; OS: Windows 10 ; Gtk 3.18.9 ; GLib  2.52.1 ; Poppler 0.54.0 cairo ; Cairo 1.15.2 , pycairo 0.12.0 ; Media: GtkImage gif player
WARNING:pympress.ui:Not starting content or presenter window full screen because there is only one monitor

```

**Comment by robertozanasi** [comment]
Setting `GDK_RENDERING=image` or `GDK_RENDERING=image` prevents the crashes (but pympress freezes when at the end of the pdf file).
